In [1]:
# Task 1

import numpy as np

print(np.__version__)

2.5.1


In [2]:
# Task 2

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# Task 3

arr = np.random.randint(1, 10, (2, 3))

print(arr)
print("Shape:", arr.shape)
print("Data type:", arr.dtype)

[[5 5 7]
 [6 1 9]]
Shape: (2, 3)
Data type: int32


In [4]:
# Task 4

arr = np.linspace(0, 10, 50)

print(arr)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [5]:
# Task 5

list1 = [1, 4, 6]
list2 = [3, 5, 7]

list_result = []

for i in range(len(list1)):
    list_result.append(list1[i] + list2[i])

array1 = np.array([1, 4, 6])
array2 = np.array([3, 5, 7])

array_result = array1 + array2

print("Python list addition:", list_result)
print("NumPy array addition:", array_result)

Python list addition: [4, 9, 13]
NumPy array addition: [ 4  9 13]


In [6]:
# Task 6

zeros = np.zeros((3, 4))

print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# Task 7

ones = np.ones((2, 5))

print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
# Task 8

nums = np.arange(10, 51, 5)

print(nums)

[10 15 20 25 30 35 40 45 50]


In [9]:
# Task 9

identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# Task 10 

arr = np.random.randint(1, 21, (4, 4))

print(arr)

[[14 15 19  9]
 [11  2 18  2]
 [20  8  2  7]
 [17 20  9  8]]


In [11]:
# Task 11

arr = np.arange(1, 16)

print(arr[3:9])

[4 5 6 7 8 9]


In [12]:
# Task 12

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr)
print(arr[1, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [13]:
# Task 13

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print(arr)
print(arr[2:, 2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[11 12]
 [15 16]]


In [14]:
# Task 14

arr = np.random.randint(10, 51, (5, 5))

print(arr)

arr[0] = 100

print(arr)

[[10 18 33 18 28]
 [11 17 43 29 38]
 [21 33 42 47 12]
 [22 32 19 34 44]
 [29 31 34 32 19]]
[[100 100 100 100 100]
 [ 11  17  43  29  38]
 [ 21  33  42  47  12]
 [ 22  32  19  34  44]
 [ 29  31  34  32  19]]


In [15]:
# Task 15

arr = np.array([12, 15, 2, 5, 7, 8, 4, 19, 22, 3])

filtered_arr = arr[arr > 5]

print(filtered_arr)

[12 15  7  8 19 22]
