In [1]:
# Task 1.1

import numpy as np

ages = np.array([25, 30, 18, 35, 22, 40, 17])

adults = ages[ages >= 18]

print("Adults:", adults)

Adults: [25 30 18 35 22 40]


In [2]:
# Task 1.2

ages = np.array([25, 30, 18, 35, 22, 40, 17])

young_adults = ages[(ages > 20) & (ages < 35)]

print("Young Adults:", young_adults)

Young Adults: [25 30 22]


In [3]:
# Task 1.3

names = np.array(["Alice", "Bob", "Charlie", "David", "Eve"])

select = names[
    np.char.startswith(names, "A") |
    np.char.startswith(names, "E")
]

print(select)

['Alice' 'Eve']


In [4]:
# Task 2.1

temperatures = np.array([28, 32, 25, 35, 30, 22, 38])

is_hot = temperatures > 30

hot_temperatures = temperatures[is_hot]

print("Mask:", is_hot)
print("Hot temperatures:", hot_temperatures)

Mask: [False  True False  True False False  True]
Hot temperatures: [32 35 38]


In [5]:
# Task 2.2

temperatures = np.array([28, 32, 25, 35, 30, 22, 38])

is_hot = temperatures > 30

temperatures[is_hot] = 31

print("Mask:", is_hot)
print("Updated temperatures:", temperatures)

Mask: [False  True False  True False False  True]
Updated temperatures: [28 31 25 31 30 22 31]


In [6]:
# Task 2.3

scores = np.array([65, 80, 72, 90, 55, 78])

grades = np.where(scores >= 75, "Pass", "Fail")

print("Grades:", grades)

Grades: ['Fail' 'Pass' 'Fail' 'Pass' 'Fail' 'Pass']


In [7]:
# Task 3.1

numbers_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

numbers_2d = numbers_1d.reshape(3, 4)

print(numbers_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
# Task 3.2

numbers_2d = np.array([[ 1, 2, 3, 4], 
                       [ 5, 6, 7, 8],
                       [ 9, 10, 11 , 12]])

numbers_1d = numbers_2d.reshape(-1)

print(numbers_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
# Task 3.3

values = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

values_2d = values.reshape(5, -1)

print(values_2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [10]:
# Task 4.1

prices = np.array([10, 20, 30])

prices_inc = prices + 5

print(prices_inc)

[15 25 35]


In [11]:
# Task 4.2

sales = np.array([[10, 20],
                  [15, 25],
                  [12, 18]])

bonuses = np.array([2, 3, 1])

broadcasting = sales + bonuses.reshape(3, 1)

print(broadcasting)

[[12 22]
 [18 28]
 [13 19]]


In [12]:
# Task 4.3

sales = np.array([[10, 20],
                  [15, 25],
                  [12, 18]])

tax_rates = np.array([0.1, 0.05])

broadcasting = sales * tax_rates.reshape(1, 2)

print(broadcasting)

[[1.   1.  ]
 [1.5  1.25]
 [1.2  0.9 ]]
