In [1]:
# Task 1

import numpy as np

arr1 = np.array([
    [1, 5, 7],
    [4, 9, 2],
    [6, 10, 14]
])

arr2 = np.array([
    [11, 15, 12],
    [14, 19, 21],
    [16, 15, 17]
])

print("Addition:\n", arr1 + arr2)
print("\nSubtraction:\n", arr1 - arr2)
print("\nMultiplication:\n", arr1 * arr2)
print("\nDivision:\n", arr1 / arr2)

Addition:
 [[12 20 19]
 [18 28 23]
 [22 25 31]]

Subtraction:
 [[-10 -10  -5]
 [-10 -10 -19]
 [-10  -5  -3]]

Multiplication:
 [[ 11  75  84]
 [ 56 171  42]
 [ 96 150 238]]

Division:
 [[0.09090909 0.33333333 0.58333333]
 [0.28571429 0.47368421 0.0952381 ]
 [0.375      0.66666667 0.82352941]]


In [2]:
# Task 2

arr = np.random.randint(1,26, (3,3))

print(arr)

print("Square Root:\n", np.sqrt(arr))      
print("\nLogarithm (base e):\n", np.log(arr)) 
print("\nExponential:\n", np.exp(arr))  

[[ 6 22 24]
 [21 24 12]
 [11  7 16]]
Square Root:
 [[2.44948974 4.69041576 4.89897949]
 [4.58257569 4.89897949 3.46410162]
 [3.31662479 2.64575131 4.        ]]

Logarithm (base e):
 [[1.79175947 3.09104245 3.17805383]
 [3.04452244 3.17805383 2.48490665]
 [2.39789527 1.94591015 2.77258872]]

Exponential:
 [[4.03428793e+02 3.58491285e+09 2.64891221e+10]
 [1.31881573e+09 2.64891221e+10 1.62754791e+05]
 [5.98741417e+04 1.09663316e+03 8.88611052e+06]]


In [3]:
# Task 3

arr = np.array([1, 5, 7, 9, 11])

print("Sine:", np.sin(arr))               
print("Cosine:", np.cos(arr))             
print("Tangent:", np.tan(arr)) 

Sine: [ 0.84147098 -0.95892427  0.6569866   0.41211849 -0.99999021]
Cosine: [ 0.54030231  0.28366219  0.75390225 -0.91113026  0.0044257 ]
Tangent: [   1.55740772   -3.38051501    0.87144798   -0.45231566 -225.95084645]


In [4]:
# Task 4

arr = np.array([2, 4, 6, 9, 13])

normalized_arr = (arr - np.mean(arr)) / np.std(arr)

print("Normalized array:", normalized_arr)

Normalized array: [-1.24101046 -0.72392277 -0.20683508  0.56879646  1.60297184]


In [5]:
# Task 5

def euclidean_distance(x1, y1, x2, y2):
    distance = np.sqrt(
        np.pow(x2 - x1, 2) + np.pow(y2 - y1, 2)
    )

    return distance


result = euclidean_distance(4, 9, 8, 12)

print("Distance:", result)

Distance: 5.0


In [6]:
# Task 6

arr1 = np.array([5, 7, 9])
arr2 = np.array([3, 5, 8])

arr1_2d = arr1.reshape(1, 3)
arr2_2d = arr2.reshape(1, 3)

horizontal = np.concatenate((arr1_2d, arr2_2d), axis=1)
vertical = np.concatenate((arr1_2d, arr2_2d), axis=0)

print("Horizontal:\n", horizontal)
print("\nVertical:\n", vertical)

Horizontal:
 [[5 7 9 3 5 8]]

Vertical:
 [[5 7 9]
 [3 5 8]]


In [7]:
# Task 7

arr1 = np.array([[1, 3, 5],
                 [4, 7, 9]])

arr2 = np.array([[12, 13, 15],
                 [2, 17, 19]])

arr3 = np.array([[16, 21, 25],
                 [24, 27, 29]])

vstack = np.vstack((arr1, arr2, arr3))

print("Vertical stack:\n", vstack)
print("\nVertical split:\n", np.vsplit(vstack, 3))

hstack = np.hstack((arr1, arr2, arr3))

print("Horizontal stack:\n", hstack)
print("\nHorizontal split:\n", np.hsplit(hstack, 3))

Vertical stack:
 [[ 1  3  5]
 [ 4  7  9]
 [12 13 15]
 [ 2 17 19]
 [16 21 25]
 [24 27 29]]

Vertical split:
 [array([[1, 3, 5],
       [4, 7, 9]]), array([[12, 13, 15],
       [ 2, 17, 19]]), array([[16, 21, 25],
       [24, 27, 29]])]
Horizontal stack:
 [[ 1  3  5 12 13 15 16 21 25]
 [ 4  7  9  2 17 19 24 27 29]]

Horizontal split:
 [array([[1, 3, 5],
       [4, 7, 9]]), array([[12, 13, 15],
       [ 2, 17, 19]]), array([[16, 21, 25],
       [24, 27, 29]])]


In [8]:
# Task 8

arr = np.array([[1, 3, 6, 8],
                [4, 7, 9, 11]])

print("split:\n", np.hsplit(arr, 4))

split:
 [array([[1],
       [4]]), array([[3],
       [7]]), array([[6],
       [9]]), array([[ 8],
       [11]])]


In [9]:
# Task 9

arr1 = np.array([
    [1, 2],
    [3, 4]
])

arr2 = np.array([
    [5, 6],
    [7, 8]
])

concatenated = np.concatenate((arr1, arr2))
stacked = np.stack((arr1, arr2))
horizontal = np.hstack((arr1, arr2))

print("Concatenate:\n", concatenated)
print("\nStack:\n", stacked)
print("\nHorizontal stack:\n", horizontal)

Concatenate:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Stack:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Horizontal stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [10]:
# Task 10

arr = np.array([
    [[1, 3], [5, 7]],
    [[9, 11], [13, 15]]
])

flattened_arr = arr.reshape(-1)

print("\nFlattened array:\n", flattened_arr)

original_shape = flattened_arr.reshape(2, 2, 2)

print("\nReshaped to original shape:\n", original_shape)


Flattened array:
 [ 1  3  5  7  9 11 13 15]

Reshaped to original shape:
 [[[ 1  3]
  [ 5  7]]

 [[ 9 11]
  [13 15]]]


In [11]:
# Task 11

arr = np.array([3, 5, 8, 11, 13, 17])

maximum = np.max(arr)
minimum = np.min(arr)

maximum_index = np.where(arr == maximum)
minimum_index = np.where(arr == minimum)

print("Index of maximum:", maximum_index[0])
print("Index of minimum:", minimum_index[0])

Index of maximum: [5]
Index of minimum: [0]


In [12]:
# Task 12

arr = np.array([
    [8, 3, 6, 1],
    [4, 11, 9, 7]
])

print("Original array:\n", arr)

print("\nSorted by columns:\n", np.sort(arr, axis=0))

print("\nSorted by rows:\n", np.sort(arr, axis=1))

Original array:
 [[ 8  3  6  1]
 [ 4 11  9  7]]

Sorted by columns:
 [[ 4  3  6  1]
 [ 8 11  9  7]]

Sorted by rows:
 [[ 1  3  6  8]
 [ 4  7  9 11]]


In [13]:
# Task 13

arr = np.random.randint(1, 31, (2, 4))

print("Array:\n", arr)
print("Mean:", np.mean(arr))    
print("Median:", np.median(arr)) 
print("Standard Deviation:", np.std(arr)) 
print("Variance:", np.var(arr))

Array:
 [[12 12 18 25]
 [26 23 14  3]]
Mean: 16.625
Median: 16.0
Standard Deviation: 7.381353195722313
Variance: 54.484375


In [14]:
# Task 14

arr = np.array([15, 13, 11, 18, 21, 5, 7, 9, 17])

positions = np.where(arr > 10)

print("Indexes:", positions[0])
print("Numbers greater than 10:", arr[positions])

Indexes: [0 1 2 3 4 8]
Numbers greater than 10: [15 13 11 18 21 17]


In [15]:
# Task 15

arr = np.random.randint(-10, 21, (4, 4))

positive = np.sum(arr > 0)
negative = np.sum(arr < 0)
zero = np.sum(arr == 0)

print("Array:\n", arr)
print("Positive:", positive)
print("Negative:", negative)
print("Zero:", zero)

Array:
 [[ 14   4   0  18]
 [ 10   1   6  20]
 [ 14  19 -10  -3]
 [  4   8  15 -10]]
Positive: 12
Negative: 3
Zero: 1
